// Downloads the icons Nova uses from Iconify (Solar, "linear" style) and saves
// them inside the project, so the app never needs the internet to draw an icon.
//
//   node scripts/vendor-icons.mjs
//
// To add an icon: add its name below and run the script again.
import { writeFileSync } from 'node:fs';

const PREFIX = 'solar';
const ICONS = [
  // main menu
  'chat-round-dots', 'checklist-minimalistic', 'wallet', 'database', 'bot',
  'shield-check', 'settings', 'sidebar-minimalistic',
  // chat bar
  'paperclip', 'add-circle', 'microphone', 'arrow-up', 'soundwave', 'cpu',
  'stars', 'lightbulb-bolt', 'alt-arrow-down', 'stop-circle', 'volume-loud',
  // general
  'close-circle', 'check-circle', 'refresh', 'bell', 'trash-bin-minimalistic',
  'pen', 'folder', 'layers', 'link-round', 'user-circle', 'calendar', 'target',
  'pie-chart-2', 'transfer-horizontal', 'document-text', 'upload-minimalistic',
  'code', 'clock-circle', 'key-minimalistic', 'info-circle', 'danger-triangle',
  'eye', 'command', 'logout-2', 'play-circle',
].map((name) => `${name}-linear`);

const url = `https://api.iconify.design/${PREFIX}.json?icons=${ICONS.join(',')}`;
const res = await fetch(url, { headers: { 'User-Agent': 'nova-vendor-icons' } });
if (!res.ok) throw new Error(`Iconify answered ${res.status}`);
const data = await res.json();

const missing = ICONS.filter((name) => !data.icons?.[name]);
if (missing.length) throw new Error(`Not found in ${PREFIX}: ${missing.join(', ')}`);

const lines = ICONS.map((name) => {
  const short = name.replace(/-linear$/, '');
  return `  ${JSON.stringify(short)}: ${JSON.stringify(data.icons[name].body)},`;
});
const source = `// GENERATED by scripts/vendor-icons.mjs from the "${PREFIX}" set (linear). Do not edit by hand.
// Solar icons by 480 Design, CC BY 4.0.
export const ICONS = {
${lines.join('\n')}
} as const;

export type IconName = keyof typeof ICONS;
`;
writeFileSync(new URL('../src/icons/solar.ts', import.meta.url), source);
console.log(`Saved ${ICONS.length} icons.`);
