// Downloads the brand logos Nova shows for its connectors from Iconify and saves
// them inside the project, so the app never needs the internet to draw a logo.
//
//   node scripts/vendor-brands.mjs
//
// To change a logo: edit the map below and run the script again.
// "logos" are full-colour; "simple-icons" are one-colour (drawn in the text colour).
import { writeFileSync } from 'node:fs';

const BRANDS = {
  anytype: 'simple-icons:anytype',
  apple_calendar: 'simple-icons:apple',
  apple_contacts: 'simple-icons:apple',
  apple_health: 'simple-icons:apple',
  apple_music: 'simple-icons:applemusic',
  apple_notes: 'simple-icons:apple',
  dropbox: 'logos:dropbox',
  gcalendar: 'logos:google-calendar',
  gcontacts: 'logos:google-icon',
  gdrive: 'logos:google-drive',
  github_notifications: 'simple-icons:github',
  gmail: 'logos:google-gmail',
  gmail_imap: 'logos:google-gmail',
  google_tasks: 'simple-icons:googletasks',
  hackernews: 'logos:ycombinator',
  imessage: 'simple-icons:imessage',
  news_rss: 'simple-icons:rss',
  notion: 'simple-icons:notion',
  obsidian: 'logos:obsidian-icon',
  outlook: 'simple-icons:microsoftoutlook',
  slack: 'logos:slack-icon',
  spotify: 'logos:spotify-icon',
  strava: 'simple-icons:strava',
  whatsapp: 'logos:whatsapp-icon',
};

const bySet = {};
for (const full of new Set(Object.values(BRANDS))) {
  const [set, name] = full.split(':');
  (bySet[set] ??= []).push(name);
}

const fetched = {};
for (const [set, names] of Object.entries(bySet)) {
  const res = await fetch(`https://api.iconify.design/${set}.json?icons=${names.join(',')}`, {
    headers: { 'User-Agent': 'nova-vendor-brands' },
  });
  if (!res.ok) throw new Error(`Iconify answered ${res.status} for ${set}`);
  const data = await res.json();
  for (const name of names) {
    const icon = data.icons?.[name];
    if (!icon) continue;
    fetched[`${set}:${name}`] = {
      body: icon.body,
      width: icon.width ?? data.width ?? 24,
      height: icon.height ?? data.height ?? 24,
      mono: set === 'simple-icons',
    };
  }
}

const missing = Object.entries(BRANDS).filter(([, full]) => !fetched[full]);
if (missing.length) {
  console.log('Not found (these will use a generic icon):');
  for (const [id, full] of missing) console.log(`  ${id}: ${full}`);
}

const lines = Object.entries(BRANDS)
  .filter(([, full]) => fetched[full])
  .map(([id, full]) => `  ${JSON.stringify(id)}: ${JSON.stringify(fetched[full])},`);
const source = `// GENERATED by scripts/vendor-brands.mjs from Iconify ("logos" and "simple-icons"). Do not edit by hand.
// Brand logos belong to their owners and are shown only to identify each service.
export interface BrandLogo {
  body: string;
  width: number;
  height: number;
  /** One-colour logo: drawn in the text colour instead of its own colours. */
  mono: boolean;
}

export const BRANDS: Record<string, BrandLogo> = {
${lines.join('\n')}
};
`;
writeFileSync(new URL('../src/icons/brands.ts', import.meta.url), source);
console.log(`Saved ${lines.length} logos to src/icons/brands.ts`);
